version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-token
      - INFLUXDB_ORG=my-org
      - INFLUXDB_BUCKET=metrics
      - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/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
    depends_on:
      - influxdb

  frontend:
    build: ./frontend
    ports:
      - "5173:4173"
  
  simulator:
    build: ./simulator
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend


  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpass
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token

volumes:
  influxdb-data:
